export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          role: "superadmin" | "admin" | "member";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: "superadmin" | "admin" | "member";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: "superadmin" | "admin" | "member";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          name: string;
          slug: string;
          dealer_name: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          franchise: string | null;
          status: "draft" | "active" | "completed" | "cancelled";
          start_date: string | null;
          end_date: string | null;
          sale_days: number | null;
          budget: number | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          dealer_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          franchise?: string | null;
          status?: "draft" | "active" | "completed" | "cancelled";
          start_date?: string | null;
          end_date?: string | null;
          sale_days?: number | null;
          budget?: number | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          dealer_name?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          franchise?: string | null;
          status?: "draft" | "active" | "completed" | "cancelled";
          start_date?: string | null;
          end_date?: string | null;
          sale_days?: number | null;
          budget?: number | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_members: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          role: "owner" | "manager" | "member";
          joined_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          role?: "owner" | "manager" | "member";
          joined_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          user_id?: string;
          role?: "owner" | "manager" | "member";
          joined_at?: string;
        };
        Relationships: [];
      };
      event_config: {
        Row: {
          id: string;
          event_id: string;
          doc_fee: number | null;
          tax_rate: number | null;
          pack: number | null;
          jde_commission_pct: number | null;
          rep_commission_pct: number | null;
          mail_campaign_name: string | null;
          mail_pieces_sent: number | null;
          target_units: number | null;
          target_gross: number | null;
          target_pvr: number | null;
          washout_threshold: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          doc_fee?: number | null;
          tax_rate?: number | null;
          pack?: number | null;
          jde_commission_pct?: number | null;
          rep_commission_pct?: number | null;
          mail_campaign_name?: string | null;
          mail_pieces_sent?: number | null;
          target_units?: number | null;
          target_gross?: number | null;
          target_pvr?: number | null;
          washout_threshold?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          doc_fee?: number | null;
          tax_rate?: number | null;
          pack?: number | null;
          jde_commission_pct?: number | null;
          rep_commission_pct?: number | null;
          mail_campaign_name?: string | null;
          mail_pieces_sent?: number | null;
          target_units?: number | null;
          target_gross?: number | null;
          target_pvr?: number | null;
          washout_threshold?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roster: {
        Row: {
          id: string;
          event_id: string;
          name: string;
          phone: string | null;
          email: string | null;
          role: "sales" | "team_leader" | "fi_manager" | "closer" | "manager";
          team: string | null;
          commission_pct: number | null;
          confirmed: boolean;
          active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          role?: "sales" | "team_leader" | "fi_manager" | "closer" | "manager";
          team?: string | null;
          commission_pct?: number | null;
          confirmed?: boolean;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          role?: "sales" | "team_leader" | "fi_manager" | "closer" | "manager";
          team?: string | null;
          commission_pct?: number | null;
          confirmed?: boolean;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lenders: {
        Row: {
          id: string;
          event_id: string;
          name: string;
          buy_rate_pct: number | null;
          max_advance: number | null;
          notes: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          name: string;
          buy_rate_pct?: number | null;
          max_advance?: number | null;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          name?: string;
          buy_rate_pct?: number | null;
          max_advance?: number | null;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      vehicle_inventory: {
        Row: {
          id: string;
          event_id: string;
          hat_number: number | null;
          stock_number: string | null;
          vin: string | null;
          year: number | null;
          make: string | null;
          model: string | null;
          trim: string | null;
          body_style: string | null;
          color: string | null;
          mileage: number | null;
          age_days: number | null;
          drivetrain: string | null;
          acquisition_cost: number | null;
          jd_trade_clean: number | null;
          jd_retail_clean: number | null;
          asking_price_115: number | null;
          asking_price_120: number | null;
          asking_price_125: number | null;
          asking_price_130: number | null;
          profit_115: number | null;
          profit_120: number | null;
          profit_125: number | null;
          profit_130: number | null;
          retail_spread: number | null;
          sold_price: number | null;
          sold_date: string | null;
          sold_to: string | null;
          salesperson_id: string | null;
          status: "available" | "sold" | "hold" | "pending" | "wholesale";
          label: string | null;
          notes: string | null;
          photo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          hat_number?: number | null;
          stock_number?: string | null;
          vin?: string | null;
          year?: number | null;
          make?: string | null;
          model?: string | null;
          trim?: string | null;
          body_style?: string | null;
          color?: string | null;
          mileage?: number | null;
          age_days?: number | null;
          drivetrain?: string | null;
          acquisition_cost?: number | null;
          jd_trade_clean?: number | null;
          jd_retail_clean?: number | null;
          asking_price_115?: number | null;
          asking_price_120?: number | null;
          asking_price_125?: number | null;
          asking_price_130?: number | null;
          profit_115?: number | null;
          profit_120?: number | null;
          profit_125?: number | null;
          profit_130?: number | null;
          retail_spread?: number | null;
          sold_price?: number | null;
          sold_date?: string | null;
          sold_to?: string | null;
          salesperson_id?: string | null;
          status?: "available" | "sold" | "hold" | "pending" | "wholesale";
          label?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          hat_number?: number | null;
          stock_number?: string | null;
          vin?: string | null;
          year?: number | null;
          make?: string | null;
          model?: string | null;
          trim?: string | null;
          body_style?: string | null;
          color?: string | null;
          mileage?: number | null;
          age_days?: number | null;
          drivetrain?: string | null;
          acquisition_cost?: number | null;
          jd_trade_clean?: number | null;
          jd_retail_clean?: number | null;
          asking_price_115?: number | null;
          asking_price_120?: number | null;
          asking_price_125?: number | null;
          asking_price_130?: number | null;
          profit_115?: number | null;
          profit_120?: number | null;
          profit_125?: number | null;
          profit_130?: number | null;
          retail_spread?: number | null;
          sold_price?: number | null;
          sold_date?: string | null;
          sold_to?: string | null;
          salesperson_id?: string | null;
          status?: "available" | "sold" | "hold" | "pending" | "wholesale";
          label?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sales_deals: {
        Row: {
          id: string;
          event_id: string;
          vehicle_id: string | null;
          deal_number: number | null;
          sale_day: number | null;
          sale_date: string | null;
          customer_name: string | null;
          customer_zip: string | null;
          customer_phone: string | null;
          stock_number: string | null;
          vehicle_year: number | null;
          vehicle_make: string | null;
          vehicle_model: string | null;
          vehicle_type: string | null;
          vehicle_cost: number | null;
          new_used: "New" | "Used" | "Certified";
          trade_year: number | null;
          trade_make: string | null;
          trade_model: string | null;
          trade_type: string | null;
          trade_mileage: number | null;
          trade_acv: number | null;
          trade_payoff: number | null;
          salesperson: string | null;
          salesperson_pct: number | null;
          salesperson_id: string | null;
          second_salesperson: string | null;
          second_sp_pct: number | null;
          second_sp_id: string | null;
          selling_price: number | null;
          front_gross: number | null;
          lender: string | null;
          rate: number | null;
          finance_type: "retail" | "lease" | "cash";
          reserve: number | null;
          warranty: number | null;
          gap: number | null;
          aftermarket_1: number | null;
          aftermarket_2: number | null;
          doc_fee: number | null;
          fi_total: number | null;
          back_gross: number | null;
          total_gross: number | null;
          pvr: number | null;
          is_washout: boolean;
          washout_amount: number | null;
          jde_gross: number | null;
          dealer_gross: number | null;
          source: string | null;
          funded: boolean;
          status: "pending" | "funded" | "unwound" | "cancelled";
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          vehicle_id?: string | null;
          deal_number?: number | null;
          sale_day?: number | null;
          sale_date?: string | null;
          customer_name?: string | null;
          customer_zip?: string | null;
          customer_phone?: string | null;
          stock_number?: string | null;
          vehicle_year?: number | null;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_type?: string | null;
          vehicle_cost?: number | null;
          new_used?: "New" | "Used" | "Certified";
          trade_year?: number | null;
          trade_make?: string | null;
          trade_model?: string | null;
          trade_type?: string | null;
          trade_mileage?: number | null;
          trade_acv?: number | null;
          trade_payoff?: number | null;
          salesperson?: string | null;
          salesperson_pct?: number | null;
          salesperson_id?: string | null;
          second_salesperson?: string | null;
          second_sp_pct?: number | null;
          second_sp_id?: string | null;
          selling_price?: number | null;
          front_gross?: number | null;
          lender?: string | null;
          rate?: number | null;
          finance_type?: "retail" | "lease" | "cash";
          reserve?: number | null;
          warranty?: number | null;
          gap?: number | null;
          aftermarket_1?: number | null;
          aftermarket_2?: number | null;
          doc_fee?: number | null;
          fi_total?: number | null;
          back_gross?: number | null;
          total_gross?: number | null;
          pvr?: number | null;
          is_washout?: boolean;
          washout_amount?: number | null;
          jde_gross?: number | null;
          dealer_gross?: number | null;
          source?: string | null;
          funded?: boolean;
          status?: "pending" | "funded" | "unwound" | "cancelled";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          vehicle_id?: string | null;
          deal_number?: number | null;
          sale_day?: number | null;
          sale_date?: string | null;
          customer_name?: string | null;
          customer_zip?: string | null;
          customer_phone?: string | null;
          stock_number?: string | null;
          vehicle_year?: number | null;
          vehicle_make?: string | null;
          vehicle_model?: string | null;
          vehicle_type?: string | null;
          vehicle_cost?: number | null;
          new_used?: "New" | "Used" | "Certified";
          trade_year?: number | null;
          trade_make?: string | null;
          trade_model?: string | null;
          trade_type?: string | null;
          trade_mileage?: number | null;
          trade_acv?: number | null;
          trade_payoff?: number | null;
          salesperson?: string | null;
          salesperson_pct?: number | null;
          salesperson_id?: string | null;
          second_salesperson?: string | null;
          second_sp_pct?: number | null;
          second_sp_id?: string | null;
          selling_price?: number | null;
          front_gross?: number | null;
          lender?: string | null;
          rate?: number | null;
          finance_type?: "retail" | "lease" | "cash";
          reserve?: number | null;
          warranty?: number | null;
          gap?: number | null;
          aftermarket_1?: number | null;
          aftermarket_2?: number | null;
          doc_fee?: number | null;
          fi_total?: number | null;
          back_gross?: number | null;
          total_gross?: number | null;
          pvr?: number | null;
          is_washout?: boolean;
          washout_amount?: number | null;
          jde_gross?: number | null;
          dealer_gross?: number | null;
          source?: string | null;
          funded?: boolean;
          status?: "pending" | "funded" | "unwound" | "cancelled";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      mail_tracking: {
        Row: {
          id: string;
          event_id: string;
          zip_code: string;
          town: string | null;
          pieces_sent: number;
          day_1: number;
          day_2: number;
          day_3: number;
          day_4: number;
          day_5: number;
          day_6: number;
          day_7: number;
          day_8: number;
          day_9: number;
          day_10: number;
          day_11: number;
          day_12: number;
          total_responses: number;
          response_rate: number | null;
          sold_from_mail: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          zip_code: string;
          town?: string | null;
          pieces_sent?: number;
          day_1?: number;
          day_2?: number;
          day_3?: number;
          day_4?: number;
          day_5?: number;
          day_6?: number;
          day_7?: number;
          day_8?: number;
          day_9?: number;
          day_10?: number;
          day_11?: number;
          day_12?: number;
          total_responses?: number;
          response_rate?: number | null;
          sold_from_mail?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          zip_code?: string;
          town?: string | null;
          pieces_sent?: number;
          day_1?: number;
          day_2?: number;
          day_3?: number;
          day_4?: number;
          day_5?: number;
          day_6?: number;
          day_7?: number;
          day_8?: number;
          day_9?: number;
          day_10?: number;
          day_11?: number;
          day_12?: number;
          total_responses?: number;
          response_rate?: number | null;
          sold_from_mail?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      daily_metrics: {
        Row: {
          id: string;
          event_id: string;
          sale_day: number;
          sale_date: string | null;
          total_ups: number;
          total_sold: number;
          total_gross: number | null;
          total_front: number | null;
          total_back: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          sale_day: number;
          sale_date?: string | null;
          total_ups?: number;
          total_sold?: number;
          total_gross?: number | null;
          total_front?: number | null;
          total_back?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          sale_day?: number;
          sale_date?: string | null;
          total_ups?: number;
          total_sold?: number;
          total_gross?: number | null;
          total_front?: number | null;
          total_back?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      commissions: {
        Row: {
          id: string;
          event_id: string;
          salesperson_id: string | null;
          salesperson_name: string;
          full_deals: number;
          half_deals: number;
          total_front_gross: number | null;
          total_back_gross: number | null;
          total_gross: number | null;
          commission_rate: number | null;
          commission_earned: number | null;
          pack_deductions: number | null;
          bonus: number | null;
          chargeback_total: number | null;
          net_pay: number | null;
          status: "draft" | "approved" | "paid";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          salesperson_id?: string | null;
          salesperson_name: string;
          full_deals?: number;
          half_deals?: number;
          total_front_gross?: number | null;
          total_back_gross?: number | null;
          total_gross?: number | null;
          commission_rate?: number | null;
          commission_earned?: number | null;
          pack_deductions?: number | null;
          bonus?: number | null;
          chargeback_total?: number | null;
          net_pay?: number | null;
          status?: "draft" | "approved" | "paid";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          salesperson_id?: string | null;
          salesperson_name?: string;
          full_deals?: number;
          half_deals?: number;
          total_front_gross?: number | null;
          total_back_gross?: number | null;
          total_gross?: number | null;
          commission_rate?: number | null;
          commission_earned?: number | null;
          pack_deductions?: number | null;
          bonus?: number | null;
          chargeback_total?: number | null;
          net_pay?: number | null;
          status?: "draft" | "approved" | "paid";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chargebacks: {
        Row: {
          id: string;
          event_id: string;
          deal_id: string | null;
          salesperson_id: string | null;
          amount: number;
          reason: string | null;
          chargeback_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          deal_id?: string | null;
          salesperson_id?: string | null;
          amount: number;
          reason?: string | null;
          chargeback_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          deal_id?: string | null;
          salesperson_id?: string | null;
          amount?: number;
          reason?: string | null;
          chargeback_date?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          event_id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: Record<string, unknown> | null;
          new_values: Record<string, unknown> | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_values?: Record<string, unknown> | null;
          new_values?: Record<string, unknown> | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          old_values?: Record<string, unknown> | null;
          new_values?: Record<string, unknown> | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      v_event_kpis: {
        Row: {
          event_id: string;
          event_name: string;
          dealer_name: string | null;
          event_status: string;
          total_deals: number;
          funded_deals: number;
          total_front_gross: number;
          total_back_gross: number;
          total_gross: number;
          avg_front_gross: number;
          avg_back_gross: number;
          avg_pvr: number;
          total_vehicles: number;
          available_vehicles: number;
          sold_vehicles: number;
          hold_vehicles: number;
          washout_count: number;
          washout_total: number;
          mail_pieces_sent: number;
          mail_total_responses: number;
          mail_response_pct: number;
          team_size: number;
          target_units: number | null;
          target_gross: number | null;
          target_pvr: number | null;
        };
        Relationships: [];
      };
      v_salesperson_stats: {
        Row: {
          event_id: string;
          salesperson_id: string | null;
          salesperson_name: string | null;
          salesperson_role: string | null;
          commission_pct: number | null;
          total_deals: number;
          full_deals: number;
          split_deals: number;
          weighted_front_gross: number;
          total_back_gross: number;
          total_gross: number;
          avg_pvr: number;
          washouts: number;
        };
        Relationships: [];
      };
      v_mail_response_stats: {
        Row: {
          event_id: string;
          zip_codes_targeted: number;
          total_pieces: number;
          total_responses: number;
          overall_response_pct: number;
          total_sold_from_mail: number;
        };
        Relationships: [];
      };
      v_daily_sales: {
        Row: {
          event_id: string;
          sale_day: number;
          sale_date: string | null;
          deals_count: number;
          day_front_gross: number;
          day_back_gross: number;
          day_total_gross: number;
          day_avg_pvr: number;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_event_member: {
        Args: { p_event_id: string };
        Returns: boolean;
      };
      is_event_role: {
        Args: { p_event_id: string; p_roles: string[] };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

// ============================================================
// Convenience type aliases for common use across components
// ============================================================
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Views<T extends keyof Database["public"]["Views"]> =
  Database["public"]["Views"][T]["Row"];

// Named exports for direct import
export type Event = Tables<"events">;
export type EventMember = Tables<"event_members">;
export type EventConfig = Tables<"event_config">;
export type Vehicle = Tables<"vehicle_inventory">;
export type Deal = Tables<"sales_deals">;
export type RosterMember = Tables<"roster">;
export type Lender = Tables<"lenders">;
export type MailTracking = Tables<"mail_tracking">;
export type DailyMetric = Tables<"daily_metrics">;
export type Commission = Tables<"commissions">;
export type Chargeback = Tables<"chargebacks">;
export type AuditLog = Tables<"audit_logs">;
export type EventKPI = Views<"v_event_kpis">;
export type SalespersonStat = Views<"v_salesperson_stats">;
export type MailResponseStat = Views<"v_mail_response_stats">;
export type DailySale = Views<"v_daily_sales">;
